import type { Card, SuitCard, SuitName } from './types.js';

export interface PlayedCard {
  playerId: string;
  card: Card;
}

export interface TrickResult {
  winner: PlayedCard;
  /** Skull King capture bonus generated by this trick, awarded to the winner (subject to their bid being matched). */
  bonusPoints: number;
}

/**
 * The led suit is set only by the first card played, and only if it's a plain/trump suit
 * card. A special card (Pirate/Escape/Mermaid/Skull King) led establishes no suit — nobody
 * is constrained to follow anything for the rest of that trick.
 */
export function getLedSuit(playedCards: PlayedCard[]): SuitName | null {
  const first = playedCards[0];
  if (!first) return null;
  return first.card.kind === 'suit' ? first.card.suit : null;
}

/** Special cards are always legal to play; suit cards must follow the led suit if the hand has one. */
export function getLegalCards(hand: Card[], ledSuit: SuitName | null): Card[] {
  if (ledSuit === null) return [...hand];
  const matching = hand.filter((c) => c.kind === 'suit' && c.suit === ledSuit);
  if (matching.length === 0) return [...hand];
  const special = hand.filter((c) => c.kind !== 'suit');
  return [...matching, ...special];
}

/**
 * Card hierarchy (highest to lowest, absent the Skull King):
 *   Pirate > Mermaid > Jolly Roger (trump) > led suit > other suits > Escape (always loses)
 * With the Skull King in play:
 *   - Skull King alone beats everything, including Pirates.
 *   - A Pirate captures the Skull King (the one flip in the hierarchy — see note below).
 *   - A Mermaid "beguiles" the Skull King and wins outright, overriding even a Pirate.
 * Ties among same-tier cards (e.g. multiple Pirates, or an all-Escape trick) go to whichever
 * was played first.
 *
 * Note: the build spec this game was implemented from states Pirates "lose to ... the Skull
 * King", which would make the "Pirate captures the Skull King" bonus (also specified) mathematically
 * unreachable. This implementation flips that one matchup (Pirate beats Skull King, absent a
 * Mermaid) so the stated bonus scoring is actually achievable — this matches the common real-world
 * Skull King ruleset. Worth confirming against your physical rulebook.
 */
export function resolveTrick(playedCards: PlayedCard[]): TrickResult {
  if (playedCards.length === 0) throw new Error('Cannot resolve an empty trick');

  const nonEscapes = playedCards.filter((p) => p.card.kind !== 'escape');
  if (nonEscapes.length === 0) {
    return { winner: playedCards[0], bonusPoints: 0 };
  }

  const skullKing = nonEscapes.find((p) => p.card.kind === 'skull_king');
  const mermaids = nonEscapes.filter((p) => p.card.kind === 'mermaid');
  const pirates = nonEscapes.filter((p) => p.card.kind === 'pirate');

  if (skullKing) {
    if (mermaids.length > 0) return { winner: mermaids[0], bonusPoints: 150 }; // 50 base + 100 mermaid-beguiles bonus
    if (pirates.length > 0) return { winner: pirates[0], bonusPoints: 100 }; // 50 base + 50 pirate-captures bonus
    return { winner: skullKing, bonusPoints: 50 }; // base capture bonus
  }

  if (mermaids.length > 0) return { winner: mermaids[0], bonusPoints: 0 };
  if (pirates.length > 0) return { winner: pirates[0], bonusPoints: 0 };

  // Only plain suit / trump cards remain in contention.
  let ledSuit = getLedSuit(playedCards);
  if (ledSuit === null) {
    // Leading card was an Escape and nothing else set a suit — fall back to the first
    // suited card actually played, so the trick still has a well-defined winner.
    const firstSuited = nonEscapes.find((p) => p.card.kind === 'suit');
    ledSuit = firstSuited ? (firstSuited.card as SuitCard).suit : null;
  }

  const trumps = nonEscapes.filter((p) => p.card.kind === 'suit' && p.card.suit === 'jolly_roger');
  const followingLed = nonEscapes.filter((p) => p.card.kind === 'suit' && p.card.suit === ledSuit);
  const contenders = trumps.length > 0 ? trumps : followingLed.length > 0 ? followingLed : nonEscapes;

  const winner = contenders.reduce((best, current) => {
    const bestVal = best.card.kind === 'suit' ? best.card.value : 0;
    const curVal = current.card.kind === 'suit' ? current.card.value : 0;
    return curVal > bestVal ? current : best;
  });

  return { winner, bonusPoints: 0 };
}
